fix(docs): modify broken reflection example
deepkit/deepkit-framework pull request #559
Opened 2024-03-13 18:56 UTC by lionelhorn

### Summary of changes
Fixed code and imports of example

### Relinquishment of Rights

Please mark following checkbox to confirm that you relinquish all rights of your changes:

- [x] I waive and relinquish all rights regarding this changes (including code, text, and images) to Deepkit UG (limited), Germany. This changes (including code, text, and images) are under MIT license without name attribution, copyright notice, and permission notice requirement.

2024-03-13 19:19 UTC, marcus-sa commented on website/src/pages/documentation/runtime-types/getting-started.md
> +const reflection = ReflectionClass.from(typeOf<User>());
```suggestion
const reflection = ReflectionClass.from<User>();
```

2024-03-13 19:21 UTC, marcus-sa requested changes

2024-03-13 19:21 UTC, marcus-sa commented on website/src/pages/documentation/runtime-types/getting-started.md
> +import { cast, MinLength, ReflectionClass, typeOf } from '@deepkit/type';
```suggestion
import { cast, MinLength, ReflectionClass } from '@deepkit/type';
```

2024-07-11 10:42 UTC, lionelhorn commented on website/src/pages/documentation/runtime-types/getting-started.md
> +const reflection = ReflectionClass.from(typeOf<User>());
Fixed in latest commit.

2024-07-11 10:42 UTC, lionelhorn commented on website/src/pages/documentation/runtime-types/getting-started.md
> +import { cast, MinLength, ReflectionClass, typeOf } from '@deepkit/type';
Fixed in latest commit.

2024-07-11 11:00 UTC, closed without merging

2024-07-11 11:00 UTC, lionelhorn commented
Closing this in favor of https://github.com/deepkit/deepkit-framework/pull/599

(Couldn't find a way to pass commitlint test, as past commits had a not accepted scope)